CREATE TABLE REGIONS (
	REGION_ID SERIAL PRIMARY KEY,
	REGION_NAME VARCHAR(255)
)

ALTER TABLE REGIONS ADD COLUMN REGION_X VARCHAR(255)

ALTER TABLE REGIONS RENAME COLUMN REGION_X TO REGION_XX

ALTER TABLE REGIONS ALTER COLUMN REGION_XX TYPE VARCHAR(25)

ALTER TABLE REGIONS ALTER COLUMN REGION_XX TYPE INTEGER USING REGION_XX::INTEGER 

CREATE TABLE COUNTRIES (
	COUNTRY_ID CHAR(2),
	COUNTRY_NAME VARCHAR(255),
	REGION_ID INTEGER,
	FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);
ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRY_ID_PK PRIMARY KEY (COUNTRY_ID)

CREATE TABLE COUNTRIES (
	COUNTRY_ID CHAR(2) PRIMARY KEY,
	COUNTRY_NAME VARCHAR(255),
	REGION_ID INTEGER,
	FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES(1,'ARTIC');
INSERT INTO REGIONS (REGION_NAME) 
VALUES
('ANTARTIC'),
('TARTANTIC');

UPDATE REGIONS SET REGION_NAME = 'ARAB' WHERE REGION_ID = 6

DELETE REGIONS 