SELECT * FROM REGIONS;
SELECT * FROM DEPARTEMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM COUNTRIES;


SELECT * FROM DEPARTEMENTS a LEFT JOIN LOCATIONS b
	ON a.LOCATION_ID = b.LOCATION_ID
	LEFT JOIN COUNTRIES c 
	ON b.COUNTRY_ID = c.COUNTRY_ID;

==Soal 1. Informasi jumlah department di tiap regions==

SELECT * FROM DEPARTEMENTS WHERE LOCATION_ID IN
	(SELECT LOCATION_ID FROM LOCATIONS a, COUNTRIES b
	WHERE a.COUNTRY_ID = b.COUNTRY_ID
	AND b.REGION_ID = 1 );
	
SELECT REGION_ID,  COUNT(DEPARTEMENT_ID)DEPARTEMENT_ID
	FROM DEPARTEMENTS a LEFT JOIN LOCATIONS b
	ON a.LOCATION_ID = b.LOCATION_ID 
	LEFT JOIN COUNTRIES c 
	ON b.COUNTRY_ID = c.COUNTRY_ID
	GROUP BY REGION_ID;

	
SELECT REGION_ID, (
	SELECT COUNT(c.DEPARTEMENT_ID)
	FROM COUNTRIES a LEFT JOIN LOCATIONS b
		ON a.COUNTRY_ID = b.COUNTRY_ID 
		LEFT JOIN DEPARTEMENTS c 
		ON b.LOCATION_ID = c.LOCATION_ID
			WHERE e.REGION_ID = e.REGION_ID ) AS TOTAL_DEPARTEMENT
			FROM REGIONS e;

==Soal 2. Informasi jumlah department tiap countries==

SELECT COUNTRY_ID, (
	SELECT COUNT(b.DEPARTEMENT_ID)
	FROM LOCATIONS a LEFT JOIN DEPARTEMENTS b
	ON a.LOCATION_ID = b.LOCATION_ID 
		WHERE c.COUNTRY_ID = c.COUNTRY_ID ) AS TOTAL_COUNTRY
		FROM COUNTRIES c;
	

==Soal 3. Informasi jumlah employee tiap department==

SELECT DEPARTEMENT_ID, COUNT(EMPLOYEE_ID)
	FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID;

==Soal 4. Informasi jumlah employee tiap region==

SELECT e.REGION_ID, COUNT(EMPLOYEE_ID)EMPLOYEE_ID
	FROM EMPLOYEES a LEFT JOIN DEPARTEMENTS b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID 
	LEFT JOIN LOCATIONS c 
	ON b.DEPARTEMENT_ID = c.LOCATION_ID
		LEFT JOIN COUNTRIES d
		ON c.COUNTRY_ID = d.COUNTRY_ID
			LEFT JOIN REGIONS e
			ON d.REGION_ID = e.REGION_ID
			GROUP BY e.REGION_ID;


==Soal 5. Informasi jumlah employee tiap countries==

SELECT d.COUNTRY_ID, COUNT(EMPLOYEE_ID)EMPLOYEE_ID
	FROM EMPLOYEES a LEFT JOIN DEPARTEMENTS b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID 
	LEFT JOIN LOCATIONS c 
	ON b.DEPARTEMENT_ID = c.LOCATION_ID
		LEFT JOIN COUNTRIES d
		ON c.COUNTRY_ID = d.COUNTRY_ID
		GROUP BY d.COUNTRY_ID;

==Soal 6. Informasi salary tertinggi tiap department==

SELECT b.DEPARTEMENT_ID, b.DEPARTEMENT_NAME, MAX(SALARY)SALARY
	FROM EMPLOYEES a LEFT JOIN DEPARTEMENTS b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY b.DEPARTEMENT_ID;
	
SELECT a.DEPARTEMENT_ID, a.DEPARTEMENT_NAME, MAX(SALARY)SALARY
	FROM DEPARTEMENTS a LEFT JOIN EMPLOYEES b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY a.DEPARTEMENT_ID;


==Soal 7. Informasi salary terendah tiap department==

SELECT b.DEPARTEMENT_ID, b.DEPARTEMENT_NAME, MIN(SALARY)SALARY
	FROM EMPLOYEES a LEFT JOIN DEPARTEMENTS b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY b.DEPARTEMENT_ID;

SELECT a.DEPARTEMENT_ID, a.DEPARTEMENT_NAME, MIN(SALARY)SALARY
	FROM DEPARTEMENTS a LEFT JOIN EMPLOYEES b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY a.DEPARTEMENT_ID;

==Soal 8. Informasi salary rata-rata tiap department==

SELECT b.DEPARTEMENT_ID, b.DEPARTEMENT_NAME, AVG(SALARY)SALARY
	FROM EMPLOYEES a LEFT JOIN DEPARTEMENTS b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY b.DEPARTEMENT_ID;
	
SELECT a.DEPARTEMENT_ID, a.DEPARTEMENT_NAME, AVG(SALARY)SALARY
	FROM DEPARTEMENTS a LEFT JOIN EMPLOYEES b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY a.DEPARTEMENT_ID;
	
==Soal 9. Informasi jumlah mutasi pegawai tiap deparment==

SELECT a.DEPARTEMENT_NAME, COUNT(*) AS JUMLAH_MUTASI
	FROM DEPARTEMENTS a LEFT JOIN EMPLOYEES b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	JOIN JOB_HISTORY c
		ON b.EMPLOYEE_ID = c.EMPLOYEE_ID
		GROUP BY a.DEPARTEMENT_NAME;
	
==Soal 10. Informasi jumlah mutasi pegawai berdasarkan srole-jobs==

SELECT a.JOB_TITLE, COUNT(*) AS ROLE_JOB
	FROM JOBS a LEFT JOIN EMPLOYEES b
	ON a.JOB_ID = b.JOB_ID
	GROUP BY a.JOB_TITLE;
	
	
==Soal 11. Informasi jumlah employee yang sering dimutasi==

SELECT EMPLOYEE_ID, COUNT(*) AS JUMLAH_KEMUNCULAN
	FROM JOB_HISTORY 
	GROUP BY EMPLOYEE_ID
		ORDER BY JUMLAH_KEMUNCULAN DESC
		LIMIT 3;


==Soal 12. Informasi jumlah employee berdasarkan Srole jobs-nya==

SELECT a.JOB_TITLE, COUNT(*) AS JUMLAH_EMPLOYEE
	FROM JOBS a LEFT JOIN EMPLOYEES b 
	ON a.JOB_ID = b.JOB_ID
	GROUP BY a.JOB_TITLE;


==Soal 13. Informasi employee paling lama bekerja di tiap deparment==

SELECT a.DEPARTEMENT_NAME, AGE(END_DATE, START_DATE) AS LAMA_BEKERJA
	FROM DEPARTEMENTS a LEFT JOIN JOB_HISTORY b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID;

==Soal 14. Informasi employee baru masuk kerja di tiap department==

SELECT a.DEPARTEMENT_NAME, MAX(HIRE_DATE) AS MASUK_KERJA
	FROM DEPARTEMENTS a LEFT JOIN EMPLOYEES b
	ON a.DEPARTEMENT_ID = b.DEPARTEMENT_ID
	GROUP BY a.DEPARTEMENT_NAME;
	
SELECT DEPARTEMENT

==Soal 15. Informasi lama bekerja tiap employee dalam tahun dan jumlah mutasi history-nya==

SELECT a.EMPLOYEE_ID, AGE(END_DATE, START_DATE) AS LAMA_BEKERJA
	FROM EMPLOYEES a LEFT JOIN JOB_HISTORY b
	ON a.EMPLOYEE_ID = b.EMPLOYEE_ID
		LEFT JOIN 
		ORDER BY LAMA_BEKERJA;

