SELECT * FROM REGIONS r INNER JOIN COUNTRIES c 
	ON r.REGION_ID = c.REGION_ID;

SELECT * FROM COUNTRIES r LEFT JOIN REGIONS c 
	ON r.REGION_ID = c.REGION_ID;
	
SELECT * FROM REGIONS r RIGHT JOIN COUNTRIES c 
	ON r.REGION_ID = c.REGION_ID;

SELECT COUNTRY_ID, COUNTRY_NAME, r.REGION_ID, r.REGION_NAME FROM REGIONS r
	RIGHT JOIN COUNTRIES c 
	ON r.REGION_ID = c.REGION_ID;

SELECT c.COUNTRY_ID, COUNTRY_NAME, r.REGION_ID, r.REGION_NAME, LOCATION_ID, STREET_ADDRESS
	FROM REGIONS r
	LEFT JOIN COUNTRIES c 
	ON r.REGION_ID = c.REGION_ID
	LEFT JOIN LOCATIONS l ON c.COUNTRY_ID = c.COUNTRY_ID;

==============================RIGHTJOIN===============================================
SELECT c.COUNTRY_ID, COUNTRY_NAME, r.REGION_ID, r.REGION_NAME, LOCATION_ID, STREET_ADDRESS
	FROM REGIONS r
	RIGHT JOIN COUNTRIES c 
	ON r.REGION_ID = c.REGION_ID
	RIGHT JOIN LOCATIONS l ON c.COUNTRY_ID = c.COUNTRY_ID;

SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES
	GROUP BY MANAGER_ID;

SELECT DEPARTEMENT_ID, SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID;

SELECT DEPARTEMENT_ID, SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID
	HAVING SUM(SALARY) >= 6500;

SELECT DEPARTEMENT_ID, MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID;

SELECT DEPARTEMENT_ID, MAX(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID;

SELECT DEPARTEMENT_ID, AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTEMENT_ID;
	
<D%> ===AWALAN HURUF D=======
<%D%> ===HURUF BISA TENGAH AWAL AKHIR======
<%D> ===HURUF DIAKHIR D=====
SELECT FIRST_NAME FROM EMPLOYEES
	WHERE FIRST_NAME LIKE 'D%';

==================SUBQUERY=====================

SELECT * FROM DEPARTEMENTS WHERE LOCATION_ID IN (
	SELECT LOCATION_ID FROM LOCATIONS l
	JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
	WHERE c.REGION_ID = 2
);

SELECT * FROM LOCATIONS WHERE COUNTRY_ID IN (
	SELECT COUNTRY_ID FROM COUNTRIES c
	JOIN REGIONS r ON c.REGION_ID = r.REGION_ID
	WHERE r.REGION_ID = 1
);







