/*View*/
DROP VIEW TOTAL_EMPLOYEE_BY_COUNTRY

CREATE OR REPLACE VIEW TOTAL_EMPLOYEE_BY_COUNTRY AS
	SELECT t.COUNTRY_NAME, t.CITY, d.DEPARTEMENT_ID, d.DEPARTEMENT_NAME, 
	COUNT(EMPLOYEE_ID)TOTAL_EMPLOYEE
	FROM EMPLOYEES e, DEPARTEMENTS d,
		( 
			SELECT r.REGION_ID, REGION_NAME, c.COUNTRY_ID, COUNTRY_NAME, CITY, l.LOCATION_ID
			FROM REGIONS r, COUNTRIES c, LOCATIONS l
			WHERE r.REGION_ID = c.REGION_ID 
			AND c.COUNTRY_ID = l.COUNTRY_ID ) t
				WHERE e.DEPARTEMENT_ID = d.DEPARTEMENT_ID
				AND d.LOCATION_ID = t.LOCATION_ID
					GROUP BY t.COUNTRY_NAME, t.CITY, d.DEPARTEMENT_ID, d.DEPARTEMENT_NAME
			
SELECT * FROM TOTAL_EMPLOYEE_BY_COUNTRY
WHERE CITY = 'London'
		
		
/*MENCARI BONUS SEMASA KERJANYA*/

SELECT MASA_KERJA, SUM(BONUS)BONUS_PER_MASA_KERJA FROM ( ==CATETAN INI NAMA KOLOM
	SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, 
	EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) MASA_KERJA, ==EKSTRAK ITU PEMISAH
		CASE WHEN EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) >= 25 THEN SALARY * 5 ==KAYA IFELSE
		WHEN EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) < 25 THEN SALARY * 2 END BONUS
		FROM EMPLOYEES) t
			GROUP BY MASA_KERJA
			ORDER BY MASA_KERJA
			
/*TIPE DUA MASA KERJA*/

SELECT SUM(MK_SATU) " 8 <= MASA KERJA <= 13",
SUM(MK_DUA) " 14 <= MASA KERJA <= 17 ",
SUM(MK_TIGA) " 18 <= MASA KERJA <= 22 "
	FROM (
	SELECT 
		CASE WHEN EXTRACT (YEAR FROM AGE(NOW(), HIRE_DATE)) >= 8
		AND EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) <= 13
		THEN COUNT(EMPLOYEES) END MK_SATU,
			CASE WHEN EXTRACT (YEAR FROM AGE(NOW(), HIRE_DATE)) >= 13
			AND EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) <= 17
			THEN COUNT(EMPLOYEES) END MK_DUA,
				CASE WHEN EXTRACT (YEAR FROM AGE(NOW(), HIRE_DATE)) >= 17
				AND EXTRACT(YEAR FROM AGE(NOW(), HIRE_DATE)) <= 22
				THEN COUNT(EMPLOYEES) END MK_TIGA
FROM EMPLOYEES
GROUP BY HIRE_DATE) t




